global:
  # How frequently to scrape targets by default.
  scrape_interval: 15s #[<duration> | default = 1m ]

  # How long until a scrape request times out.
  scrape_timeout: 10s #[<duration> | default = 10s ]

  # How frequently to evaluate rules.
  evaluation_interval: 15s #[<duration> | default = 1m ]

  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  #    external_labels:
  #      [ <labelname>: <labelvalue> ... ]

  # File to which PromQL queries are logged.
  # Reloading the configuration will reopen the file.
#    [ query_log_file: <string> ]

# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
#rule_files:
#  [ - <filepath_glob> ... ]

# A list of scrape configurations.
#scrape_configs:
#  [ - <scrape_config> ... ]

# Alerting specifies settings related to the Alertmanager.
alerting:
  alert_relabel_configs:
#      [ - <relabel_config> ... ]
  alertmanagers:
    - static_configs:
        - targets:
#           - alertmanager:9093

# Settings related to the remote write feature.
remote_write:
#  [ - <remote_write> ... ]

# Settings related to the remote read feature.
remote_read:
#  [ - <remote_read> ... ]

# Storage related settings that are runtime reloadable.
#storage:
#  [ - <exemplars> ... ]

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

#TODO: This job is for the container application but its returning error 400 bad request
#  - job_name: 'spring-actuator'
#    metrics_path: "/actuator/prometheus"
#    scrape_interval: 5s
#    scrape_timeout: 3s
#    scheme: http
#    static_configs:
#      - targets: [ 'spring_app_sds:8080' ]

# This job is for local machine, it's necessary to change the ip
  - job_name: 'application'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.237.66:8080' ]
