spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
  data:
    mongodb:
      uri: mongodb://root:example@127.0.0.1:27017/system-design-study?authSource=admin
      database: system-design-study
  redis:
    password: Redis2019!

#Observability
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
